<html>
<head>
    <title>disclaimer | klekt seller advice</title>

    <link rel="icon" href="img/icon.png">

    <meta charset="UTF-8">

    <!-- Main stylesheet -->
    <link rel="stylesheet" href="css/main.css">
</head>
<body>
    <div id="disclaimer">
        <a href="index.php">go back ⬅️</a>

        <p>
            presentedby or KLEKT are not affiliated with this application in any way.
            this application is merely something created by a user of the KLEKT platform. <br>
            <hr>
            the application uses <strong>public</strong> sources to generate "advice" or "statistics" for sellers on KLEKT.
            the sellers are free to do whatever they want with this information.
            <hr>
            it should also be noted that the data generated by this application may not always be accurate.
            sellers should <strong>never</strong> assume that the information from this application is correct.
            as such, the creator and any contributor(s) to this application should never be held accountable for any damages that the generated information may cause
            <hr>
            KLEKT: <a href="https://www.presentedbyklekt.com/">https://www.presentedbyklekt.com/</a>
        </p>
    </div>
</body>
</html>